export type Plant = {
  id: string;
  name: string;
  slug: string;
  description: string;
  flor: string;
  riego: string;
  suelo: string;
  florece: string;
  exposicion: string;
  fruta: string;
  tamano: string;
  category: string;
  nativo: boolean;
  price: number;
  amount: number;
  available: boolean;
  image: string;
  images: string[];
};